### ISSUE TITLE
Ort anzeigen

### ISSUE THREAD

**Issue by tim-peters** [Patrick-Fieger/Radar-for-Adaptive-Club-Recommender#11]
Laut Designs/Konzept soll der User oben sehen in welchem Ort/Stadt er sich grade befindet.

ToDo:
- API erweitern & mit Server-Team absprechen
- In Umsetzung einbauen

**Comment by tim-peters** [comment]
Wie ist hier der Stand?

**Comment by seheradi** [comment]
Hab mich die Woche in angular.js eingearbeitet und (bisher erfolglos) einem geeigneten npm gesucht. Setz mich dann doch mit OpenStreetMap auseinander. Denke, dass ichs spätestens morgen Abend umgesetzt hab.

**Comment by seheradi** [comment]
Umsetzung mit Open MapQuest API; http://open.mapquestapi.com/geocoding/
Noch Probleme mit der callback-Funktion 
FRAGEN: soll/muss der Stadtname innerhalb der scope definiert werden? Oder wird ohnehin nur mit den Geodaten gearbeitet (zur Umkreissuche etc.)? 
Im Prinzip ist die Frage, ob die Anzeige des Stadtnamens ein reines UI-Feature, oder auch anders relevant ist.

Außerdem, da Suchfeld: Muss/Soll das Ganze auch in die umgekehrte Richtung funktionieren (Eingabe Stadtname, Ermittlung entsprechender Geodaten)?

**Comment by seheradi** [comment]
Den Ort anzuzeigen funktioniert

**Comment by tim-peters** [comment]
Nach meinem Kenntnissstand ist das zur Zeit ein reines "UI-Feature", da die Rückwärtssuche zwar im Konzept steht, aber im Prototyp noch nicht umgesetzt werden soll. "Später" wäre es dann auch umgekehrt relevant - für dieses Semester ist es so perfekt :)
